### ISSUE TITLE
How to generate a synthetic video by an audio and an image?

### ISSUE THREAD

**Issue by NoHateAnymore** [megvii-research/MM2022-ViCoPerceptualHeadGeneration#1]
Hi, thanks for your working.
But I didn't see how to generate a synthetic video by an audio and an image, how to do it plz.

**Comment by P2Oileen** [comment]
Hi Minghy!
Since this repo only contains parts that are different from the original project [vico_challenge_baseline](https://github.com/dc3ea9f/vico_challenge_baseline), you can replace the content of the original project according to the instructions in our [readme](https://github.com/megvii-research/MM2022-ViCoPerceptualHeadGeneration#readme), and then run it according to the instructions of the original project.
